### ISSUE TITLE
evaluate.py 

### ISSUE THREAD

**Issue by Urian-oy** [it-hao/MITNet#2]
![image](https://github.com/user-attachments/assets/28d210e3-a37b-4277-b1dc-00e11e86dbb5)
When I run the test file, I get the above error message, expecting a reply

**Comment by it-hao** [comment]
> ![image](https://private-user-images.githubusercontent.com/71719371/393175213-28d210e3-a37b-4277-b1dc-00e11e86dbb5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0OTE3OTAsIm5iZiI6MTczMzQ5MTQ5MCwicGF0aCI6Ii83MTcxOTM3MS8zOTMxNzUyMTMtMjhkMjEwZTMtYTM3Yi00Mjc3LWIxZGMtMDBlMTFlODZkYmI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA2VDEzMjQ1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjMTNlMzJlODIzMDNkZDk2OTczZmZiZGI0MDEwYWU2ODRmMTZkYjUwMDE4MWY0ZTU3YWU4NjI0OWE3NzcwYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.sjr1xnKxz6aPPSdUefXRL6paE2zAXVlcd3ilrHuJcTE) When I run the test file, I get the above error message, expecting a reply
你好，这个我也看不太懂啥意思，不行的话可以加我微信 15055648306，帮你看看
